package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
)

// SetPrompt is the resolver for the setPrompt field.
func (r *mutationResolver) SetPrompt(ctx context.Context, prompt string) (string, error) {
	panic(fmt.Errorf("not implemented: SetPrompt - setPrompt"))
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello, World!", nil // Return the actual result here
}

// PromptResponse is the resolver for the promptResponse field.
func (r *queryResolver) PromptResponse(ctx context.Context, prompt string) (string, error) {
	return r.Resolver.PromptService.Generate(prompt)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
